### ISSUE TITLE
Refactor window saving/loading to be more reliable in some areas

### ISSUE THREAD

**Issue by Curtis-VL** [Curtis-VL/OVRToolkit-Issues#103]
- [ ]  Look into same process windows not being reloaded correctly. (Such as Discord vs a Discord pop-out window)
- [ ] If a window is closed, it should not default back to another window with the same process. (Such as YouTube in Chrome switching to another open Chrome window - This would cause incorrect saving)

**Comment by SirVeggie** [comment]
To elaborate, defaulting back to another window is fine (and recommended), as long as the original target is saved separately instead of getting overwritten. That original info can be used later to match again to get the closest match, instead of having the defaulted window as the new target to match against.

Use window handle to match if possible. However, make sure hwnd is not redistributed to another window by comparing saved Class and Exe info. I can assure you this will ONLY increase reliability, not decrease consistency (the actual functionality works independently from ovrt or system restarts). I promise in the name of my ~8 years of Windows automation hobbyist experience, Curtis ;)

**(Not essential)** Use window Class as an additional step in identifying a fallback window. Windows of 'similar purpose' usually have same classes. For example all popup messages created by an application very often have the same class. Using the class to limit possible matches as an additional step might help finding more accurate fallbacks.

**(Not essential)** Possible alternatives to 5-length suffix matching on the Title:
- Instead choose longest common suffix. This chooses the more accurate window if more than 1 has the same 5-length suffix.
- Use [edit distance](https://en.wikipedia.org/wiki/Edit_distance) instead to get most accurate match
  - For best results I recommend [longest common subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem)
  - Sir Veggie has the required C# code to do edit distance matching

**Comment by Curtis-VL** [comment]
Made rather major changes to window reloading logic, let me know how that goes!
