### ISSUE TITLE
Battery of devices not visible with pimax

### ISSUE THREAD

**Issue by N8ISGR8** [Curtis-VL/OVRToolkit-Issues#87]
When using a pimax hmd, vive trackers, and knuckles with toolkit, it does not display battery life of vive trackers. It does show the knuckles battery life however. If there is any solution you know of or need help with testing, I would be glad to help.

**Comment by Curtis-VL** [comment]
Hi there!

This is a PiTool bug, not an OVR Toolkit bug. :)

There's some ways around this so that devices are paired through SteamVR instead of PiTool, but they're a pain to perform!
I don't recall the exact details but it's something about allowng SteamVR to run with no headset connected and then it'll let you pair trackers to their dongles through SteamVR instead of PiTool? There's a Reddit post about it but I'm having a hard time finding it I'm afraid!

I'll close the issue as it's not specific to OVR Toolkit!
